/*DESAFIOS DE BANCO DE DADOS */
/*DESAFIO 1: UMA LISTA COM O NOME DE TODAS AS GAFANHOTAS*/
/*DESAFIO 2: UMA LISTA COM OS DADOS DE TODOS AQUELES QUE NASCERAM 01/JANEIRO/2000 E 31/DEZEMBRO/2015 */
/*DESAFIO 3: UMA LISTA COMO O NOME DE TODOS HOMENS QUE TRABALHAM COMO PROGRAMADORES.*/
/*DESAFIO 4: UMA LISTA COM OS DADOS DE TODAS AS MULHERES QUE NASCERAM NO BRASIL E QUE TÊM O NOME INICIADO COM A LETRA 'J'*/
/*DESAFIO 5: UMA LISTA COM O NOME E NACIONALIDADE DE TODOS OS HOMENS QUE TÊM SILVA NO NOME, NÃO NASCERAM NO BRASIL E PESAM MENOS DE 100KG*/
/*DESAFIO 6: QUAL É A MAIOR ALTURA ENTRE OS GAFANHOTOS HOMENS QUE MORAM NO BRASIL?*/
/*DESAFIO 7: QUAL É A MÉDIA DE PESO DOS GAFANHOTOS CADASTRADOS*/
/*DESAFIO 8: QUAL É O MENOR PESO ENTRE OS GAFANHOTOS MULHERES QUE NASCERAM FORA DO BRASIL E ENTRE 01/JAN/1990 Á 31/DEZ/1990? */
/*DESAFIO 9: QUANTAS GAFANHOTAS MULHERES TÊM MAIS DE 1.90M DE ALTURA*/